import { MediaItem, MediaType, MediaCategory } from './types';

export const ARCHIVE_ITEMS: MediaItem[] = [
  // --- SECCIÓN C.R.O (Links extraídos de leeme.txt) ---
  { 
    id: 'cro1', 
    name: 'C.R.O - Fresco', 
    url: 'https://cdn.discordapp.com/attachments/1404746778741575730/1466238646674784287/Fresco_Cenfe.mp3?ex=69970b66&is=6995b9e6&hm=4941840e57c827f8faf9ab7357de0b2a44306d2ff77dfe871ee977cbc503eabc&$0', 
    type: MediaType.AUDIO, 
    category: MediaCategory.CRO, 
    format: 'mp3' 
  },

  // --- VIDEOS ---
  { id: 'v1', name: 'Starboy Remix (Video Oficial)', url: 'https://files.catbox.moe/va1nvu.mp4', type: MediaType.VIDEO, category: [MediaCategory.OFFICIAL, MediaCategory.DUKI], format: 'mp4', subtitleUrl: 'https://files.catbox.moe/1ysq3x.srt' },
  { id: 'v2', name: 'Level Up (Prod. Estani) - Lost Media', url: 'https://files.catbox.moe/0fqzb5.mp4', type: MediaType.VIDEO, category: [MediaCategory.LOST_MEDIA, MediaCategory.DUKI], format: 'mp4' },
  { id: 'v3', name: 'Cayendo Pa Arriba (Video Oficial) - Lost Media', url: 'https://files.catbox.moe/4nxxek.mp4', type: MediaType.VIDEO, category: [MediaCategory.LOST_MEDIA, MediaCategory.DUKI], format: 'mp4' },
  { id: 'v4', name: 'Sold Out Dates (Video Oficial)', url: 'https://files.catbox.moe/6s93n0.mp4', type: MediaType.VIDEO, category: [MediaCategory.OFFICIAL, MediaCategory.DUKI], format: 'mp4' },
  { id: 'v5', name: 'Ticket (ft. Yesan, Asan) - Video', url: 'https://files.catbox.moe/2usvm9.mp4', type: MediaType.VIDEO, category: [MediaCategory.OFFICIAL, MediaCategory.DUKI], format: 'mp4' },
  { id: 'v6', name: 'aPOLLo13 (Video Oficial)', url: 'https://files.catbox.moe/g5c56g.mp4', type: MediaType.VIDEO, category: [MediaCategory.OFFICIAL, MediaCategory.DUKI], format: 'mp4' },
  { id: 'v7', name: 'En Parte... No lo sé (Video)', url: 'https://files.catbox.moe/0r3ivn.mp4', type: MediaType.VIDEO, category: [MediaCategory.OFFICIAL, MediaCategory.DUKI], format: 'mp4' },
  { id: 'v8', name: 'YaMeFui (ft. Nicki Nicole, Bizarrap)', url: 'https://files.catbox.moe/iblf4k.mp4', type: MediaType.VIDEO, category: [MediaCategory.OFFICIAL, MediaCategory.DUKI], format: 'mp4' },

  // --- AUDIOS OPTIMIZADOS ---
  { id: 'a1', name: 'Starboy Remix (Audio HQ)', url: 'https://files.catbox.moe/rcba1j.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a', subtitleUrl: 'https://files.catbox.moe/1ysq3x.srt' },
  { id: 'a2', name: 'Level Up (Audio .opus)', url: 'https://files.catbox.moe/scg3vf.opus', type: MediaType.AUDIO, category: [MediaCategory.LOST_MEDIA, MediaCategory.DUKI], format: 'opus' },
  { id: 'a3', name: 'Cayendo Pa Arriba (Audio .opus)', url: 'https://files.catbox.moe/ri3oxg.opus', type: MediaType.AUDIO, category: [MediaCategory.LOST_MEDIA, MediaCategory.DUKI], format: 'opus' },
  { id: 'a4', name: '2_50 Remix (Audio .opus)', url: 'https://files.catbox.moe/owmap1.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a5', name: 'Mericrisma (Audio .opus)', url: 'https://files.catbox.moe/xx0emk.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus', subtitleUrl: 'https://files.catbox.moe/003t76.srt' },
  { id: 'a6', name: 'Sold Out Dates (Audio)', url: 'https://files.catbox.moe/blddy4.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { 
    id: 'a7', 
    name: 'Tumbando el Club (Remix)', 
    url: 'https://files.catbox.moe/pyuv9h.opus', 
    type: MediaType.AUDIO, 
    category: [MediaCategory.OPTIMIZED, MediaCategory.CRO, MediaCategory.DUKI], 
    format: 'opus' 
  },
  { id: 'a8', name: 'WACHA (ft. KHEA)', url: 'https://files.catbox.moe/0z4b4l.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a9', name: 'Sin Frenos (ft. Eladio Carrión)', url: 'https://files.catbox.moe/a88ch1.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a10', name: 'Chico Estrella', url: 'https://files.catbox.moe/9pa8qc.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a11', name: 'GELATO (ft. Smokepurpp)', url: 'https://files.catbox.moe/329et0.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a12', name: 'Iba a Llamarte', url: 'https://files.catbox.moe/tch5fk.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a13', name: 'Deja Vú', url: 'https://files.catbox.moe/xatrpk.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a14', name: 'EO EO', url: 'https://files.catbox.moe/jhhlh9.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a15', name: 'Marca de la Cadena', url: 'https://files.catbox.moe/xh0ndy.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'a16', name: 'Por Mi Nombre', url: 'https://files.catbox.moe/2jlb0k.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { 
    id: 'a17', 
    name: 'Mojaa', 
    url: 'https://files.catbox.moe/t7fi2g.opus', 
    type: MediaType.AUDIO, 
    category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], 
    format: 'opus' 
  },

  // --- PLAYLIST SECTION ---
  { id: 'p1', name: 'DUKI - Cine', url: 'https://files.catbox.moe/1hu8bk.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { 
    id: 'p2', 
    name: 'DUKI_C.R.O - #FVCKLUV', 
    url: 'https://files.catbox.moe/j8qocp.opus', 
    type: MediaType.AUDIO, 
    category: [MediaCategory.OPTIMIZED, MediaCategory.CRO, MediaCategory.DUKI], 
    format: 'opus' 
  },
  { id: 'p3', name: 'DUKI, Aleman - Me Gusta lo Simple', url: 'https://files.catbox.moe/ydylsy.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p4', name: "DUKI, C. Tangana, Khea - It's a Vibe", url: 'https://files.catbox.moe/tgu1hv.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p5', name: 'DUKI, Lucho SSJ - La Jefatura', url: 'https://files.catbox.moe/s0tppn.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p6', name: 'DUKI x Obie WanShot - H.I.E.L.O.', url: 'https://files.catbox.moe/b70wwy.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p7', name: 'One Million Dollar Baby', url: 'https://files.catbox.moe/0pmynb.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p8', name: 'DUKI x YSY A - A Punta de Espada', url: 'https://files.catbox.moe/v24f8m.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p9', name: 'DUKI - Te Traje Flores', url: 'https://files.catbox.moe/43hpx4.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p10', name: "She Don't Give a FO (ft. Khea)", url: 'https://files.catbox.moe/hfpajy.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p11', name: 'Duki - Mi Chain De Roque', url: 'https://files.catbox.moe/2sqike.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p12', name: 'DUKI - Señorita', url: 'https://files.catbox.moe/gccrm1.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'p13', name: 'DUKI - Perdón', url: 'https://files.catbox.moe/s7juib.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },

  // --- M4A ARCHIVOS ---
  { id: 'm1', name: 'DUKI, Myke Towers - Nueva Era', url: 'https://files.catbox.moe/m9yj94.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm2', name: 'Nicki Nicole, Duki - MASCARA', url: 'https://files.catbox.moe/2wlavj.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm3', name: 'Pininfarina (Remix)', url: 'https://files.catbox.moe/vt9lro.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm4', name: 'Lucho SSJ, Duki - Casablanca', url: 'https://files.catbox.moe/unbs72.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm5', name: 'HABLAMOS MAÑANA...', url: 'https://files.catbox.moe/lrlbcr.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm6', name: 'BZRP Sessions #50', url: 'https://files.catbox.moe/lwp64w.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm7', name: 'DUKI - Ameri (Album Full)', url: 'https://files.catbox.moe/stvuhe.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm8', name: 'Antes de Perderte', url: 'https://files.catbox.moe/4su30l.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm9', name: 'GIVENCHY', url: 'https://files.catbox.moe/rgghfz.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm10', name: 'Goteo', url: 'https://files.catbox.moe/8pk8fg.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm11', name: 'Hello Cotto', url: 'https://files.catbox.moe/emstir.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm12', name: 'Rockstar', url: 'https://files.catbox.moe/2dszax.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm13', name: 'She Don\'t Give a FO (M4A)', url: 'https://files.catbox.moe/8vezqf.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm14', name: 'No me Llores (Remix)', url: 'https://files.catbox.moe/8hgifr.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'm15', name: 'RoCKSTAR 2.0', url: 'https://files.catbox.moe/k9svla.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },

  // --- OTROS & RAROS ---
  { id: 'o1', name: '2Tonos', url: 'https://files.catbox.moe/pnbixg.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o2', name: 'antes de perderte (OG)', url: 'https://files.catbox.moe/v78gkq.opus', type: MediaType.AUDIO, category: [MediaCategory.LOST_MEDIA, MediaCategory.DUKI], format: 'opus' },
  { id: 'o3', name: 'BUSCANDO Ameri', url: 'https://files.catbox.moe/gtsm5b.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o4', name: 'CALL ME MAYBE', url: 'https://files.catbox.moe/izb3ss.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o5', name: 'GiGi', url: 'https://files.catbox.moe/cpc0ic.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o6', name: 'JEFES DEL SUDOESTE', url: 'https://files.catbox.moe/hf09me.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o7', name: 'N.C.L.C', url: 'https://files.catbox.moe/6bvflp.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o8', name: 'cONTRA MI', url: 'https://files.catbox.moe/yh0leq.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o9', name: 'uNo dOs', url: 'https://files.catbox.moe/f928ks.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o10', name: 'don_t liE', url: 'https://files.catbox.moe/epguwi.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o11', name: 'Vida De Rock', url: 'https://files.catbox.moe/7hk4qz.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o12', name: '01 dE ENEro', url: 'https://files.catbox.moe/4gyb2z.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o13', name: 'Buscarte Lejos', url: 'https://files.catbox.moe/2sb5ho.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o14', name: 'C5ipher', url: 'https://files.catbox.moe/n9sq76.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o15', name: 'Ultimo Tren a Ameri', url: 'https://files.catbox.moe/ersret.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o16', name: 'Si Te Sentis Sola', url: 'https://files.catbox.moe/vh5gfw.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o17', name: 'Valentino (ft. Tobi)', url: 'https://files.catbox.moe/dikq0j.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o18', name: 'Ticket (ft. Yesan, Asan) - Vivo', url: 'https://files.catbox.moe/uz56gg.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o19', name: 'Sudor y trabajo', url: 'https://files.catbox.moe/3p4ev6.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o20', name: 'Sol (ft. Lara91k)', url: 'https://files.catbox.moe/1ndw8k.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { 
    id: 'o21', 
    name: 'hARAKiRi (ZECCA Remix)', 
    url: 'https://files.catbox.moe/e3t8zp.opus', 
    type: MediaType.AUDIO, 
    category: [MediaCategory.OPTIMIZED, MediaCategory.CRO, MediaCategory.DUKI], 
    format: 'opus' 
  },
  { id: 'o22', name: 'Unfollow (ft. Justin Quiles)', url: 'https://files.catbox.moe/t88s1w.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o23', name: 'aPOLLo13 (Audio)', url: 'https://files.catbox.moe/1dleps.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o24', name: 'Ella es mi Bitch', url: 'https://files.catbox.moe/62t2jf.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o25', name: 'En Movimiento', url: 'https://files.catbox.moe/jsdqht.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o26', name: 'Fifty Fifty (Remix)', url: 'https://files.catbox.moe/1ky0m4.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o27', name: 'Luna (ft. Asan)', url: 'https://files.catbox.moe/e84lfd.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'o28', name: 'Malbec (x Bizarrap)', url: 'https://files.catbox.moe/7ggjq3.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o29', name: 'Midtown', url: 'https://files.catbox.moe/qlp2w4.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o30', name: 'Muero de Fiesta Este Finde', url: 'https://files.catbox.moe/zahz7x.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { 
    id: 'o31', 
    name: 'hARAKiRi (Audio)', 
    url: 'https://files.catbox.moe/sffq25.opus', 
    type: MediaType.AUDIO, 
    category: [MediaCategory.OPTIMIZED, MediaCategory.CRO, MediaCategory.DUKI], 
    format: 'opus' 
  },
  { id: 'o32', name: 'Perreo Bendito (Visualizer)', url: 'https://files.catbox.moe/6743uo.m4a', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'm4a' },
  { id: 'o33', name: 'En Parte... No lo sé (Audio)', url: 'https://files.catbox.moe/oa6ma8.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o34', name: 'TROYA', url: 'https://files.catbox.moe/r6u8vn.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o35', name: 'Yo-Yo', url: 'https://files.catbox.moe/o96yyz.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o36', name: 'Golfista', url: 'https://files.catbox.moe/uw0t1b.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o37', name: 'NO ME ALCANZA', url: 'https://files.catbox.moe/bt6z8w.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o38', name: 'Ta Te Ti', url: 'https://files.catbox.moe/i20wjw.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o39', name: 'Calabasas (ft. Zell)', url: 'https://files.catbox.moe/9m0ay6.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o40', name: 'Remember Me', url: 'https://files.catbox.moe/m1dbnm.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o41', name: 'aGaRRo La PLaTa', url: 'https://files.catbox.moe/p8mmnc.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o42', name: 'Toc Psycho', url: 'https://files.catbox.moe/3cz78g.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o43', name: '[FREE] 5202 Beat', url: 'https://files.catbox.moe/h5552z.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o44', name: 'Wake Up & Bake Up', url: 'https://files.catbox.moe/pactro.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o45', name: 'No Drama', url: 'https://files.catbox.moe/2ixq23.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
  { id: 'o46', name: 'Constelación', url: 'https://files.catbox.moe/g3bwh7.opus', type: MediaType.AUDIO, category: [MediaCategory.OPTIMIZED, MediaCategory.DUKI], format: 'opus' },
];